{"level":"ERROR","date":"2019-07-29 13:00:43,836","pid":2216,"hostname":"cocodeiMac.local","message":"nodejs.SequelizeConnectionError: connect ETIMEDOUT\n    at Utils.Promise.tap.then.catch.err (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)\nFrom previous event:\n    at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)\n    at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\nFrom previous event:\n    at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)\n    at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:266:46)\n    at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)\nFrom previous event:\n    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)\n    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21\n    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)\n    at Sequelize.authenticate (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:786:17)\n    at authenticate (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:129:22)\n    at Promise.all.databases.map.database (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:49)\n    at Array.map (<anonymous>)\n    at app.beforeStart (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:33)\n    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)\n    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)\nname: \"SequelizeConnectionError\"\nparent: {\"errorno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\",\"syscall\":\"connect\",\"fatal\":true}\noriginal: {\"errorno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\",\"syscall\":\"connect\",\"fatal\":true}\npid: 2216\nhostname: cocodeiMac.local\n"}
{"paddingMessage":"[-/::1/-/11149ms GET /api/userList?]","level":"ERROR","date":"2019-07-29 14:54:54,452","pid":2258,"hostname":"cocodeiMac.local","message":"[service.user]:获取用户列表失败： { SequelizeConnectionError: connect ETIMEDOUT\n    at Utils.Promise.tap.then.catch.err (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)\nFrom previous event:\n    at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)\n    at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)\nFrom previous event:\n    at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)\n    at Object.create (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:101:28)\n    at Pool._createResource (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:308:42)\n    at Pool._dispense (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:226:12)\n    at Pool.acquire (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:455:10)\n    at promise.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:292:24)\nFrom previous event:\n    at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:291:20)\n    at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)\nFrom previous event:\n    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)\n    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21\n    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)\n    at QueryInterface.select (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/query-interface.js:1104:27)\n    at Promise.try.then.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1598:34)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\nFrom previous event:\n    at Function.findAll (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1595:8)\n    at UserService.getUserList (/Users/coco/project/support/performance-node/app/service/user.js:111:24)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n  name: 'SequelizeConnectionError',\n  parent:\n   { Error: connect ETIMEDOUT\n       at Connection._handleTimeoutError (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:171:17)\n       at ontimeout (timers.js:436:11)\n       at tryOnTimeout (timers.js:300:5)\n       at listOnTimeout (timers.js:263:5)\n       at Timer.processTimers (timers.js:223:10)\n   From previous event:\n       at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:12)\n       at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)\n   From previous event:\n       at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)\n       at Object.create (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:101:28)\n       at Pool._createResource (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:308:42)\n       at Pool._dispense (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:226:12)\n       at Pool.acquire (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:455:10)\n       at promise.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:292:24)\n   From previous event:\n       at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:291:20)\n       at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)\n   From previous event:\n       at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)\n       at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21\n       at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)\n       at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)\n       at QueryInterface.select (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/query-interface.js:1104:27)\n       at Promise.try.then.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1598:34)\n       at runCallback (timers.js:705:18)\n       at tryOnImmediate (timers.js:676:5)\n       at processImmediate (timers.js:658:5)\n   From previous event:\n       at Function.findAll (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1595:8)\n       at UserService.getUserList (/Users/coco/project/support/performance-node/app/service/user.js:111:24)\n       at process._tickCallback (internal/process/next_tick.js:68:7)\n     errorno: 'ETIMEDOUT',\n     code: 'ETIMEDOUT',\n     syscall: 'connect',\n     fatal: true },\n  original:\n   { Error: connect ETIMEDOUT\n       at Connection._handleTimeoutError (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:171:17)\n       at ontimeout (timers.js:436:11)\n       at tryOnTimeout (timers.js:300:5)\n       at listOnTimeout (timers.js:263:5)\n       at Timer.processTimers (timers.js:223:10)\n   From previous event:\n       at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:12)\n       at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)\n   From previous event:\n       at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)\n       at Object.create (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:101:28)\n       at Pool._createResource (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:308:42)\n       at Pool._dispense (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:226:12)\n       at Pool.acquire (/Users/coco/project/support/performance-node/node_modules/generic-pool/lib/Pool.js:455:10)\n       at promise.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:292:24)\n   From previous event:\n       at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:291:20)\n       at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)\n   From previous event:\n       at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)\n       at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21\n       at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)\n       at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)\n       at QueryInterface.select (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/query-interface.js:1104:27)\n       at Promise.try.then.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1598:34)\n       at runCallback (timers.js:705:18)\n       at tryOnImmediate (timers.js:676:5)\n       at processImmediate (timers.js:658:5)\n   From previous event:\n       at Function.findAll (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1595:8)\n       at UserService.getUserList (/Users/coco/project/support/performance-node/app/service/user.js:111:24)\n       at process._tickCallback (internal/process/next_tick.js:68:7)\n     errorno: 'ETIMEDOUT',\n     code: 'ETIMEDOUT',\n     syscall: 'connect',\n     fatal: true } }"}
{"paddingMessage":"[-/::1/-/11151ms GET /api/userList?]","level":"ERROR","date":"2019-07-29 14:54:54,454","pid":2258,"hostname":"cocodeiMac.local","message":"[controller.user]: 获取用户列表失败 {}"}
{"paddingMessage":"[-/::1/-/11151ms GET /api/userList?]","level":"ERROR","date":"2019-07-29 14:54:54,454","pid":2258,"hostname":"cocodeiMac.local","message":"[server error]: method = \"GET\", originalUrl = \"/api/userList?\"\n    status=404, reqParam= undefined Error: Error: SequelizeConnectionError: connect ETIMEDOUT\n    at UserController.getUserList (/Users/coco/project/support/performance-node/app/controller/user.js:50:13)"}
{"paddingMessage":"[-/127.0.0.1/-/0ms GET /]","level":"ERROR","date":"2019-07-29 14:55:08,247","pid":4049,"hostname":"cocodeiMac.local","message":"nodejs.SequelizeConnectionError: connect ETIMEDOUT\n    at Utils.Promise.tap.then.catch.err (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)\nFrom previous event:\n    at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)\n    at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\nFrom previous event:\n    at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)\n    at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:266:46)\n    at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)\nFrom previous event:\n    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)\n    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21\n    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)\n    at Sequelize.authenticate (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:786:17)\n    at authenticate (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:129:22)\n    at Promise.all.databases.map.database (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:49)\n    at Array.map (<anonymous>)\n    at app.beforeStart (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:33)\n    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)\n    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)\nname: \"SequelizeConnectionError\"\nparent: {\"errorno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\",\"syscall\":\"connect\",\"fatal\":true}\noriginal: {\"errorno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\",\"syscall\":\"connect\",\"fatal\":true}\npid: 4049\nhostname: cocodeiMac.local\n"}
{"level":"ERROR","date":"2019-07-29 14:55:27,267","pid":4088,"hostname":"cocodeiMac.local","message":"nodejs.SequelizeConnectionError: connect ETIMEDOUT\n    at Utils.Promise.tap.then.catch.err (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)\nFrom previous event:\n    at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)\n    at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\nFrom previous event:\n    at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)\n    at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:266:46)\n    at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)\nFrom previous event:\n    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)\n    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21\n    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)\n    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)\n    at Sequelize.authenticate (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:786:17)\n    at authenticate (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:129:22)\n    at Promise.all.databases.map.database (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:49)\n    at Array.map (<anonymous>)\n    at app.beforeStart (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:33)\n    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)\n    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)\nname: \"SequelizeConnectionError\"\nparent: {\"errorno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\",\"syscall\":\"connect\",\"fatal\":true}\noriginal: {\"errorno\":\"ETIMEDOUT\",\"code\":\"ETIMEDOUT\",\"syscall\":\"connect\",\"fatal\":true}\npid: 4088\nhostname: cocodeiMac.local\n"}
{"paddingMessage":"[-/127.0.0.1/-/0ms GET /]","level":"ERROR","date":"2019-07-29 19:23:53,550","pid":4710,"hostname":"cocodeiMac.local","message":"nodejs.Error: [egg-schedule] Cannot find schedule pk\n    at Application.app.runSchedule.args [as runSchedule] (/Users/coco/project/support/performance-node/node_modules/egg-schedule/app.js:91:15)\n    at AppBootHook.willReady (/Users/coco/project/support/performance-node/app.js:12:20)\n\npid: 4710\nhostname: cocodeiMac.local\n"}
{"paddingMessage":"[-/::1/-/1ms GET /index.html]","level":"ERROR","date":"2019-07-29 20:34:04,025","pid":6152,"hostname":"cocodeiMac.local","message":"nodejs.ENOENTError: ENOENT: no such file or directory, stat '/Users/coco/project/support/performance-node/app/public/index.html'\nENOENTError: ENOENT: no such file or directory, stat '/Users/coco/project/support/performance-node/app/public/index.html'\nerrno: -2\ncode: \"ENOENT\"\nsyscall: \"stat\"\npath: \"/Users/coco/project/support/performance-node/app/public/index.html\"\nname: \"ENOENTError\"\npid: 6152\nhostname: cocodeiMac.local\n"}
{"level":"ERROR","date":"2019-07-29 20:34:04,025","pid":6152,"hostname":"cocodeiMac.local","message":"catch sys with err {\"errno\":-2,\"code\":\"ENOENT\",\"syscall\":\"stat\",\"path\":\"/Users/coco/project/support/performance-node/app/public/index.html\",\"name\":\"ENOENTError\"}"}
{"paddingMessage":"[-/::1/-/0ms GET /index.html]","level":"ERROR","date":"2019-07-29 20:34:07,240","pid":6152,"hostname":"cocodeiMac.local","message":"nodejs.ENOENTError: ENOENT: no such file or directory, stat '/Users/coco/project/support/performance-node/app/public/index.html'\nENOENTError: ENOENT: no such file or directory, stat '/Users/coco/project/support/performance-node/app/public/index.html'\nerrno: -2\ncode: \"ENOENT\"\nsyscall: \"stat\"\npath: \"/Users/coco/project/support/performance-node/app/public/index.html\"\nname: \"ENOENTError\"\npid: 6152\nhostname: cocodeiMac.local\n"}
{"level":"ERROR","date":"2019-07-29 20:34:07,242","pid":6152,"hostname":"cocodeiMac.local","message":"catch sys with err {\"errno\":-2,\"code\":\"ENOENT\",\"syscall\":\"stat\",\"path\":\"/Users/coco/project/support/performance-node/app/public/index.html\",\"name\":\"ENOENTError\"}"}
