2019-07-12 14:42:58,477 ERROR 71427 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeConnectionError: Unknown database 'performance'
    at Utils.Promise.tap.then.catch.err (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
From previous event:
    at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)
    at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:266:46)
    at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)
    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)
    at Sequelize.authenticate (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:786:17)
    at authenticate (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
name: "SequelizeConnectionError"
parent: {"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'performance'"}
original: {"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'performance'"}
pid: 71427
hostname: cocodeiMac.local

2019-07-12 14:43:17,466 ERROR 71455 nodejs.SequelizeConnectionError: Unknown database 'performance'
    at Utils.Promise.tap.then.catch.err (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
From previous event:
    at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)
    at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:266:46)
    at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)
    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)
    at Sequelize.authenticate (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:786:17)
    at authenticate (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
name: "SequelizeConnectionError"
parent: {"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'performance'"}
original: {"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'performance'"}
pid: 71455
hostname: cocodeiMac.local

2019-07-12 14:44:04,326 ERROR 71499 nodejs.SequelizeConnectionError: Unknown database 'performance'
    at Utils.Promise.tap.then.catch.err (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
From previous event:
    at ConnectionManager.connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:50)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at ConnectionManager._connect (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:338:8)
    at ConnectionManager.getConnection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:266:46)
    at Promise.try (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:557:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:64)
    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)
    at Sequelize.authenticate (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:786:17)
    at authenticate (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/coco/project/support/performance-node/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
name: "SequelizeConnectionError"
parent: {"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'performance'"}
original: {"code":"ER_BAD_DB_ERROR","errno":1049,"sqlState":"42000","sqlMessage":"Unknown database 'performance'"}
pid: 71499
hostname: cocodeiMac.local

2019-07-12 14:45:30,880 ERROR 71544 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Invalid default value for 'type'
    at Query.formatError (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:79:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:561:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:558:8)
    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.createTable (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/query-interface.js:279:29)
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:39)
From previous event:
    at Function.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:8)
    at Promise.each.model (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:50)
From previous event:
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Sequelize.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:709:8)
    at AppBootHook.willReady (/Users/coco/project/support/performance-node/app.js:9:26)
    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` TINYINT(1) NOT NULL DEFAULT false, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
original: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` TINYINT(1) NOT NULL DEFAULT false, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
sql: "CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` TINYINT(1) NOT NULL DEFAULT false, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"
pid: 71544
hostname: cocodeiMac.local

2019-07-12 14:47:08,008 ERROR 71608 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Invalid default value for 'type'
    at Query.formatError (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:79:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:561:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:558:8)
    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.createTable (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/query-interface.js:279:29)
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:39)
From previous event:
    at Function.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:8)
    at Promise.each.model (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:50)
From previous event:
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Sequelize.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:709:8)
    at AppBootHook.willReady (/Users/coco/project/support/performance-node/app.js:9:26)
    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
original: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
sql: "CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"
pid: 71608
hostname: cocodeiMac.local

2019-07-12 14:48:45,669 ERROR 71661 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Invalid default value for 'type'
    at Query.formatError (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:79:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:561:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:558:8)
    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.createTable (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/query-interface.js:279:29)
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:39)
From previous event:
    at Function.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:8)
    at Promise.each.model (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:50)
From previous event:
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Sequelize.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:709:8)
    at AppBootHook.willReady (/Users/coco/project/support/performance-node/app.js:9:26)
    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
original: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
sql: "CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"
pid: 71661
hostname: cocodeiMac.local

2019-07-12 14:49:19,159 ERROR 71695 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Invalid default value for 'type'
    at Query.formatError (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/coco/project/support/performance-node/node_modules/mysql2/lib/connection.js:79:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:561:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:558:8)
    at /Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/coco/project/support/performance-node/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.createTable (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/query-interface.js:279:29)
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:39)
From previous event:
    at Function.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/model.js:1128:8)
    at Promise.each.model (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:50)
From previous event:
    at Promise.try.then.then (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:722:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Sequelize.sync (/Users/coco/project/support/performance-node/node_modules/sequelize/lib/sequelize.js:709:8)
    at AppBootHook.willReady (/Users/coco/project/support/performance-node/app.js:9:26)
    at Object.callFn (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/coco/project/support/performance-node/node_modules/egg-core/lib/lifecycle.js:262:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
original: {"code":"ER_INVALID_DEFAULT","errno":1067,"sqlState":"42000","sqlMessage":"Invalid default value for 'type'","sql":"CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"}
sql: "CREATE TABLE IF NOT EXISTS `t_bas_notices` (`id` INTEGER(11) UNSIGNED NOT NULL auto_increment , `inviter` INTEGER(11) NOT NULL DEFAULT 0, `invitee` INTEGER(11) NOT NULL DEFAULT 0, `title` VARCHAR(255) NOT NULL DEFAULT '', `type` INTEGER(3) NOT NULL DEFAULT '', `status` INTEGER(3) NOT NULL DEFAULT 0, `read` INTEGER(3) NOT NULL DEFAULT 1, `create_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` TIMESTAMP NULL NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) ENGINE=InnoDB;"
pid: 71695
hostname: cocodeiMac.local

